export const sample_packages: any[] = [
  {
    id: "1",
    name: "Chakra Healing",
    price: 1000,
    practiceTime: "40minutes",
    favorite: false,
    origins: ["Costa Rica"],
    stars: 5.0,
    imageUrl: "assets/mica1.jpg",
    tags: ["Reiki"],
    videosUrl: ["1", "2", "3", "4", "5"],
  },
  {
    id: "2",
    name: "Slow Flow",
    price: 1000,
    practiceTime: "50minutes",
    favorite: false,
    origins: ["Costa Rica"],
    stars: 4.0,
    imageUrl: "assets/mica1.jpg",
    tags: ["SlowFlow"],
    videosUrl: ["1", "2", "3", "4", "5"],
  },
  {
    id: "3",
    name: "Pastelito Teaching",
    price: 7000,
    practiceTime: "50minutes",
    favorite: false,
    origins: ["Argentina"],
    stars: 5.0,
    imageUrl: "assets/pastelito.jpg",
    tags: ["Philosopy"],
    videosUrl: ["1", "2", "3", "4", "5"],
  },
  {
    id: "4",
    name: "Streching",
    price: 500,
    practiceTime: "20minutes",
    favorite: true,
    origins: ["Costa Rica"],
    stars: 3.0,
    imageUrl: "assets/stretch.JPG",
    tags: ["Viniyasa"],
    videosUrl: ["1", "2", "3", "4", "5"],
  },
  {
    id: "5",
    name: "hacer ochos",
    price: 10,
    practiceTime: "60minutes",
    favorite: false,
    origins: ["Costa Rica"],
    stars: 1.0,
    imageUrl: "assets/mica2.JPG",
    tags: ["Philosopy"],
    videosUrl: ["1", "2", "3", "4", "5"],
  },
  {
    id: "6",
    name: "Sunset Saltutation",
    price: 1000,
    practiceTime: "40minutes",
    favorite: false,
    origins: ["Costa Rica"],
    stars: 5.0,
    imageUrl: "assets/sunset.JPG",
    tags: ["Reiki"],
    videosUrl: ["1", "2", "3", "4", "5"],
  },
  {
    id: "7",
    name: "Sunset Saltutation",
    price: 1000,
    practiceTime: "50minutes",
    favorite: false,
    origins: ["Costa Rica"],
    stars: 4.0,
    imageUrl: "assets/sunset.JPG",
    tags: ["SlowFlow"],
    videosUrl: ["1", "2", "3", "4", "5"],
  },
  {
    id: "8",
    name: "Sunset Saltutation",
    price: 7000,
    practiceTime: "50minutes",
    favorite: false,
    origins: ["Argentina"],
    stars: 5.0,
    imageUrl: "assets/sunset.JPG",
    tags: ["Philosopy"],
    videosUrl: ["1", "2", "3", "4", "5"],
  },
  {
    id: "9",
    name: "Sunset Saltutation",
    price: 500,
    practiceTime: "20minutes",
    favorite: true,
    origins: ["Costa Rica"],
    stars: 3.0,
    imageUrl: "assets/sunset.JPG",
    tags: ["Viniyasa"],
    videosUrl: ["1", "2", "3", "4", "5"],
  },
  {
    id: "10",
    name: "Sunset Saltutation",
    price: 10,
    practiceTime: "60minutes",
    favorite: false,
    origins: ["Costa Rica"],
    stars: 1.0,
    imageUrl: "assets/sunset.JPG",
    tags: ["Philosopy"],
    videosUrl: ["1", "2", "3", "4", "5"],
  },
];

export const sample_tags: any[] = [
  { name: "All", count: 10 },
  { name: "PowerYoga", count: 0 },
  { name: "SlowFlow", count: 2 },
  { name: "Viniyasa", count: 2 },
  { name: "Astanga", count: 0 },
  { name: "Reiki", count: 2 },
  { name: "Philosopy", count: 4 },
];

export const sample_users:any[] = [
  {name:"Daniel Baruch",
  email:"danielb534@gmail.com",
  password:"12345",
  address:"Toronto",
  isAdmin:true,
},
{name:"Tamar Baruch",
  email:"tamar202@gmail.com",
  password:"12345",
  address:"israel",
  isAdmin:false,
},
]
